### ISSUE TITLE
请问，支持Node 14.x吗

### ISSUE THREAD

**Issue by winnochan** [wwog/wechatpay-v3-sdk#1]
如题

**Comment by wwog** [comment]
不支持，用了node16自带的加密库。自带的性能好一些




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wwog/wechatpay-v3-sdk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月3日(星期五) 晚上7:16
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[wwog/wechatpay-v3-sdk] 请问，支持Node 14.x吗 (Issue #1)





 
如题
